Bloggie.Web/Pages/Admin/Blogs/Add.cshtml.cs
using Bloggie.Web.Data;
using Bloggie.Web.Models.Domain;
using Bloggie.Web.Models.ViewModels;
using Bloggie.Web.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json;

namespace Bloggie.Web.Pages.Admin.Blogs
{
    public class AddModel : PageModel
    {
        private readonly IBlogPostRepository _IBlogPostRepository;

        [BindProperty]
        public AddBlogPost AddBlogPostRequest { get; set; }

        public AddModel(IBlogPostRepository IBlogPostRepository)
        {
            _IBlogPostRepository = IBlogPostRepository;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            var blogPost = new BlogPost()
            {
                Heading = AddBlogPostRequest.Heading,
                Content = AddBlogPostRequest.Content,
                PageTitle = AddBlogPostRequest.PageTitle,
                ShortDescription = AddBlogPostRequest.ShortDescription,
                FeatureImageUrl = AddBlogPostRequest.FeatureImageUrl,
                UrlHandle = AddBlogPostRequest.UrlHandle,
                PublishedDate = AddBlogPostRequest.PublishedDate,
                Author = AddBlogPostRequest.Author,
                Visible = AddBlogPostRequest.Visible,
            };

            await _IBlogPostRepository.AddAsync(blogPost);

            var notification = new Notification
            {
                Message = "New blog created",
                Type = Enums.NotificationType.Success
            };

            TempData["Notification"] = JsonSerializer.Serialize(notification);

            return RedirectToPage("/Admin/Blogs/List");
        }
    }
}

Bloggie.Web/Pages/Admin/Blogs/Edit.cshtml.cs
using Bloggie.Web.Data;
using Bloggie.Web.Models.Domain;
using Bloggie.Web.Models.ViewModels;
using Bloggie.Web.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;

namespace Bloggie.Web.Pages.Admin.Blogs
{
    public class EditModel : PageModel
    {
        private readonly IBlogPostRepository _IBlogPostRepository;
        [BindProperty]
        public BlogPost BlogPost { get; set; }
        public EditModel(IBlogPostRepository IBlogPostRepository)
        {
            _IBlogPostRepository = IBlogPostRepository;
        }
        public async Task OnGet(Guid id)
        {
            BlogPost = await _IBlogPostRepository.GetAsync(id);
        }

        public async Task<IActionResult> OnPostEdit()
        {
            try
            {
                await _IBlogPostRepository.UpdateAsync(BlogPost);
                ViewData["Notification"] = new Notification
                {
                    Message = "Record updated successfully",
                    Type = Enums.NotificationType.Success
                };
            }
            catch (Exception ex)
            {
                ViewData["Notification"] = new Notification
                {
                    Message = "Something went wrong!",
                    Type = Enums.NotificationType.Error
                };
            }
            

            return RedirectToPage("/Admin/Blogs/List");
        }
        
        public async Task<IActionResult> OnPostDelete()
        {
            var deleted = await _IBlogPostRepository.DeleteAsync(BlogPost.Id);

            if (deleted)
            {
                var notification = new Notification
                {
                    Message = "Blog was deleted successfully",
                    Type = Enums.NotificationType.Success
                };

                TempData["Notification"] = JsonSerializer.Serialize(notification);

                return RedirectToPage("/Admin/Blogs/List");
            }

            return Page();

        }
    }
}

Bloggie.Web/Pages/Admin/Blogs/List.cshtml.cs
using Bloggie.Web.Data;
using Bloggie.Web.Models.Domain;
using Bloggie.Web.Models.ViewModels;
using Bloggie.Web.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;

namespace Bloggie.Web.Pages.Admin.Blogs
{
    public class ListModel : PageModel
    {
        private readonly IBlogPostRepository _IBlogPostRepository;
        public List<BlogPost> BlogPosts { get; set; }
        public ListModel(IBlogPostRepository IBlogPostRepository)
        {
            _IBlogPostRepository = IBlogPostRepository;
        }
        public async Task OnGet()
        {
            var notificationJson = (string)TempData["Notification"];
            if(notificationJson != null) 
            {
                ViewData["Notification"] = JsonSerializer.Deserialize<Notification>(notificationJson);
            }

            BlogPosts = await _IBlogPostRepository.GetAllAsync();
        }
    }
}

Bloggie.Web/Pages/Admin/Blogs/Add.cshtml
@page
@model Bloggie.Web.Pages.Admin.Blogs.AddModel
@{
}

<div class="bg-secondary bg-opacity-10 py-2 mb-5">
    <div class="container">
        <h1>Add Blog Post</h1>
    </div>
</div>

<div>
    <div class="container">
        <form method="post">
            <div class="mb-3">
                <label for="heading" class="form-label">Heading</label>
                <input type="text" class="form-control" id="heading" asp-for="AddBlogPostRequest.Heading">
            </div>

            <div class="mb-3">
                <label for="heading" class="form-label">Page Title</label>
                <input type="text" class="form-control" id="pageTitle" asp-for="AddBlogPostRequest.PageTitle">
            </div>

            <div class="mb-3">
                <label for="heading" class="form-label">Content</label>
                <textarea class="form-control" id="content" asp-for="AddBlogPostRequest.Content"></textarea>
            </div>

            <div class="mb-3">
                <label for="shortDescription" class="form-label">Short Description</label>
                <input type="text" class="form-control" id="shortDescription" asp-for="AddBlogPostRequest.ShortDescription">
            </div>

            <div class="mb-3">
                <label for="featuredImageUrl" class="form-label">Featured Image Url</label>
                <input type="text" class="form-control" id="featuredImageUrl" asp-for="AddBlogPostRequest.FeatureImageUrl">
            </div>

            <div class="mb-3">
                <label for="urlHandle" class="form-label">Url Handle</label>
                <input type="text" class="form-control" id="urlHandle" asp-for="AddBlogPostRequest.UrlHandle">
            </div>

            <div class="mb-3">
                <label for="publishedDate" class="form-label">Published Date</label>
                <input type="date" class="form-control" id="publishedDate" asp-for="AddBlogPostRequest.PublishedDate">
            </div>

            <div class="mb-3">
                <label for="author" class="form-label">Author</label>
                <input type="text" class="form-control" id="author" asp-for="AddBlogPostRequest.Author">
            </div>

            <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" id="isVisible" asp-for="AddBlogPostRequest.Visible">
                <label class="form-check-label" for="isVisible">
                    Is Visible
                </label>
            </div>

            <div class="mb-3">
                <button class="btn btn-primary" type="submit">Submit</button>
            </div>

        </form>
    </div>
</div>
@section Scripts
    {
    <script>
        var editor = new FroalaEditor('#content');
    </script>
    }

Bloggie.Web/Pages/Admin/Blogs/Edit.cshtml
@page "{id:Guid}"
@model Bloggie.Web.Pages.Admin.Blogs.EditModel
@{
}

<div class="bg-secondary bg-opacity-10 py-2 mb-5">
    <div class="container">
        <h1>Edit Blog Post</h1>
    </div>
</div>

<partial name="_Notification">

@if (Model.BlogPost != null)
{
    <div>
        <div class="container">
            <form method="post">
                <div class="mb-3">
                    <label for="id" class="form-label">Id</label>
                    <input type="text" class="form-control" id="id" asp-for="BlogPost.Id" readonly>
                </div>

                <div class="mb-3">
                    <label for="heading" class="form-label">Heading</label>
                    <input type="text" class="form-control" id="heading" asp-for="BlogPost.Heading">
                </div>

                <div class="mb-3">
                    <label for="heading" class="form-label">Page Title</label>
                    <input type="text" class="form-control" id="pageTitle" asp-for="BlogPost.PageTitle">
                </div>

                <div class="mb-3">
                    <label for="heading" class="form-label">Content</label>
                    <textarea class="form-control" id="content" asp-for="BlogPost.Content"></textarea>
                </div>

                <div class="mb-3">
                    <label for="shortDescription" class="form-label">Short Description</label>
                    <input type="text" class="form-control" id="shortDescription" asp-for="BlogPost.ShortDescription">
                </div>

                <div class="mb-3">
                    <label for="featuredImageUrl" class="form-label">Featured Image Url</label>
                    <input type="text" class="form-control" id="featuredImageUrl" asp-for="BlogPost.FeatureImageUrl">
                </div>

                <div class="mb-3">
                    <label for="urlHandle" class="form-label">Url Handle</label>
                    <input type="text" class="form-control" id="urlHandle" asp-for="BlogPost.UrlHandle">
                </div>

                <div class="mb-3">
                    <label for="publishedDate" class="form-label">Published Date</label>
                    <input type="date" class="form-control" id="publishedDate" asp-for="BlogPost.PublishedDate">
                </div>

                <div class="mb-3">
                    <label for="author" class="form-label">Author</label>
                    <input type="text" class="form-control" id="author" asp-for="BlogPost.Author">
                </div>

                <div class="form-check mb-3">
                    <input class="form-check-input" type="checkbox" id="isVisible" asp-for="BlogPost.Visible">
                    <label class="form-check-label" for="isVisible">
                        Is Visible
                    </label>
                </div>

                <div class="mb-3 d-flex justify-content-between">
                    <button class="btn btn-primary" type="submit" asp-page-handler="Edit">Submit</button>
                    <button class="btn btn-danger" type="submit" asp-page-handler="Delete">Delete</button>
                </div>

            </form>
        </div>
    </div>

}
else
{
    <div class="container">
        <p>Blog Post Not Found</p>
    </div>
}

    @section Scripts
        {
        <script>
            var editor = new FroalaEditor('#content');
        </script>
    }

Bloggie.Web/Pages/Admin/Blogs/List.cshtml
@page
@model Bloggie.Web.Pages.Admin.Blogs.ListModel
@{
}

<div class="bg-secondary bg-opacity-10 py-2 mb-5">
    <div class="container">
        <h1>Blog Posts</h1>
    </div>
</div>

<partial name="_Notification">

@if(Model.BlogPosts != null && Model.BlogPosts.Any())
{
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <td>Id</td>
                    <td>Heading</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var BlogPost in Model.BlogPosts)
                {
                    <tr>
                        <td>@BlogPost.Id</td>
                        <td>@BlogPost.Heading</td>
                        <td><a href="/Admin/Blogs/Edit/@BlogPost.Id">View</a></td>

                    </tr>
                }
            </tbody>
        </table>
    </div>

} else
{
    <div class="container">
        <p>BlogPost not avaiable</p>
    </div>
}